os: linux
dist: xenial
language: csharp
mono: none
services:
- docker
env:
  global:
  - SRC_MOUNT=/usr/local/src/${REPO_NAME}
  jobs:
  - RUNTIME=win-x64
before_install:
- cd ~/build/clarkx86 && git clone https://github.com/clarkx86/common_ci-scripts.git && cd common_ci-scripts && chmod +x ./*
- REPO_NAME=$(./get_repo-name.sh $TRAVIS_REPO_SLUG)
- TAG_CLEAN=$(./get_tag_clean.sh $TRAVIS_TAG)
- ASSEMBLY_VERSION=$(./format_assembly-version.sh $TAG_CLEAN $TRAVIS_BUILD_NUMBER)
- ARTIFACT_NAME=${REPO_NAME}_${RUNTIME}_v${TAG_CLEAN}-${TRAVIS_BUILD_NUMBER}
- ./patch_assemblyinfo-version.sh ~/build/${TRAVIS_REPO_SLUG}/Properties/AssemblyInfo.cs $ASSEMBLY_VERSION
- cd ~/build/${TRAVIS_REPO_SLUG}
install:
- docker run --name mono_build -t -d -v ~/build/${TRAVIS_REPO_SLUG}:${SRC_MOUNT} -w $SRC_MOUNT mono
- docker exec mono_build nuget restore
script:
- docker exec mono_build msbuild papyrus-gui.csproj /p:Configuration=Release /p:Platform=x64
- docker exec mono_build chown -R $(id -u):$(id -g) $SRC_MOUNT
- docker stop mono_build
before_deploy:
- cd ~/build/${TRAVIS_REPO_SLUG}/bin/x64/Release
- zip ${ARTIFACT_NAME}.zip ./*
deploy:
  provider: releases
  api_key:
    secure: geZjyOpgkWaqvzgc9js4EaTwuuLuImrOXKKFDwkDspPuLnpHnsNTLOVhftKQ2DL/bTQIrlfT2uuzfttnpbRmHoPCUGtNFbuRNGoUIpgWJSsO7QiggeJPN7o9s8baAC3vhvpgJXWkGdx3ZPf65X2M9XaITgu3JhQhUiMgz4uJnKj2tWF3xIKOWUR2DoyPKvpHBDvwDb3NngYDEOU27DqVU5Q4y/EcDLeyiKi5+ERe4941DcfMv/xUDIvBToO+MixcMO53QnhOwDxCRGn4oVhRpynAbvysYb3qcuUeHnZD8co6J4i9yY8BlLVoe2uq+f+igfHkxjkwbrF6hEQEOCek0WPTjCOj9nPqw8gR3g/zTcJhsDHNiQMZL9QjpJVtpw4ACGdPBRVDyi8h/fiWC81lXqv3bybrBqTsa8xAgOB45trxIlk/w3CBOw15zfGlAEpePf2rFJ3Ol2bW2wVq4kYO3SFRn3vleAsCP0CFE5ZvI5hYcZXYEr6VgqM/uvdm9gCK0kQHlRdVa0nM8rMgQQrefgD6n/HRe/Avcb/YiF7MPdPdxZV+9pW2a9axfmyHmMKz+92w4ORuruEeZKQnvyDc30DZuHNMXK/K651FNHCK04xIB3SHBuqRfmB9Cw4lw+y+9PKs1GVTK25NRQW8zHZNebRty3CXcsQEeWeruX0WDvY=
  file: ${ARTIFACT_NAME}.zip
  on:
    repo: clarkx86/papyrus-gui
    tags: true
  skip_cleanup: true
